//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión del motor en tiempo de ejecución:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vista.Properties {
    using System;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Recursos {
        private static global::System.Resources.ResourceManager resourceMan;
        private static global::System.Globalization.CultureInfo resourceCulture;

        internal Recursos() { }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vista.Properties.Recursos", typeof(Recursos).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get { return resourceCulture; }
            set { resourceCulture = value; }
        }

        internal static System.Drawing.Bitmap FondoInicio { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("FondoInicio", resourceCulture))); } }
        internal static System.Drawing.Bitmap AvatarUsuario { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("AvatarUsuario", resourceCulture))); } }
        internal static System.Drawing.Bitmap Insignia4 { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("Insignia4", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoAgregar { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoAgregar", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoTablero { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoTablero", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoCalendario { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoCalendario", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoPanel { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoPanel", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoHitos { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoHitos", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoSalir { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoSalir", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoProductividad { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoProductividad", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoProductividadSeleccionado { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoProductividadSeleccionado", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoProyectos { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoProyectos", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoRevision { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoRevision", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoEquipo { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoEquipo", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoPanelSeleccionado { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoPanelSeleccionado", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoProyectosSeleccionado { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoProyectosSeleccionado", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoAgregarSeleccionado { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoAgregarSeleccionado", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoHitosSeleccionado { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoHitosSeleccionado", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoEquipoSeleccionado { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoEquipoSeleccionado", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoCalendarioSeleccionado { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoCalendarioSeleccionado", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoTableroSeleccionado { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoTableroSeleccionado", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoRevisionSeleccionado { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoRevisionSeleccionado", resourceCulture))); } }
        internal static System.Drawing.Bitmap IconoUsuario { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("IconoUsuario", resourceCulture))); } }
        internal static System.Drawing.Bitmap LogoSyncore { get { return ((System.Drawing.Bitmap)(ResourceManager.GetObject("LogoSyncore", resourceCulture))); } }
    }
}
