namespace Vista
{
    partial class frmConfiguracionInicial
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            this.lblTitulo = new System.Windows.Forms.Label();
            this.lblSubtitulo = new System.Windows.Forms.Label();
            this.grpEmpresa = new System.Windows.Forms.GroupBox();
            this.lblNombreEmpresa = new System.Windows.Forms.Label();
            this.txtNombreEmpresa = new System.Windows.Forms.TextBox();
            this.lblLogo = new System.Windows.Forms.Label();
            this.txtRutaLogo = new System.Windows.Forms.TextBox();
            this.btnExaminar = new System.Windows.Forms.Button();
            this.lblInformacion = new System.Windows.Forms.Label();
            this.txtInformacionGeneral = new System.Windows.Forms.TextBox();
            this.pnlAdministrador = new System.Windows.Forms.Panel();
            this.lblAdministrador = new System.Windows.Forms.Label();
            this.lblEstadoAdministrador = new System.Windows.Forms.Label();
            this.lblNombreAdministrador = new System.Windows.Forms.Label();
            this.txtNombreAdministrador = new System.Windows.Forms.TextBox();
            this.lblUsuarioAdministrador = new System.Windows.Forms.Label();
            this.txtUsuarioAdministrador = new System.Windows.Forms.TextBox();
            this.lblContrasena = new System.Windows.Forms.Label();
            this.txtContrasena = new System.Windows.Forms.TextBox();
            this.lblConfirmarContrasena = new System.Windows.Forms.Label();
            this.txtConfirmarContrasena = new System.Windows.Forms.TextBox();
            this.btnGuardar = new System.Windows.Forms.Button();
            this.btnSalir = new System.Windows.Forms.Button();
            this.grpEmpresa.SuspendLayout();
            this.pnlAdministrador.SuspendLayout();
            this.SuspendLayout();
            this.lblTitulo.AutoSize = true;
            this.lblTitulo.Font = new System.Drawing.Font("Segoe UI Semibold", 20F, System.Drawing.FontStyle.Bold);
            this.lblTitulo.ForeColor = System.Drawing.Color.FromArgb(11, 55, 104);
            this.lblTitulo.Location = new System.Drawing.Point(34, 25);
            this.lblTitulo.Name = "lblTitulo";
            this.lblTitulo.Size = new System.Drawing.Size(337, 37);
            this.lblTitulo.Text = "Configuración inicial de Syncore";
            this.lblSubtitulo.AutoSize = true;
            this.lblSubtitulo.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblSubtitulo.ForeColor = System.Drawing.Color.FromArgb(91, 108, 128);
            this.lblSubtitulo.Location = new System.Drawing.Point(38, 68);
            this.lblSubtitulo.Name = "lblSubtitulo";
            this.lblSubtitulo.Size = new System.Drawing.Size(468, 15);
            this.lblSubtitulo.Text = "Configure los datos de la empresa y el primer administrador antes de utilizar el sistema.";
            this.grpEmpresa.Controls.Add(this.txtInformacionGeneral);
            this.grpEmpresa.Controls.Add(this.lblInformacion);
            this.grpEmpresa.Controls.Add(this.btnExaminar);
            this.grpEmpresa.Controls.Add(this.txtRutaLogo);
            this.grpEmpresa.Controls.Add(this.lblLogo);
            this.grpEmpresa.Controls.Add(this.txtNombreEmpresa);
            this.grpEmpresa.Controls.Add(this.lblNombreEmpresa);
            this.grpEmpresa.Font = new System.Drawing.Font("Segoe UI Semibold", 10F, System.Drawing.FontStyle.Bold);
            this.grpEmpresa.Location = new System.Drawing.Point(41, 105);
            this.grpEmpresa.Name = "grpEmpresa";
            this.grpEmpresa.Size = new System.Drawing.Size(728, 245);
            this.grpEmpresa.TabStop = false;
            this.grpEmpresa.Text = "Datos de la empresa";
            this.lblNombreEmpresa.AutoSize = true;
            this.lblNombreEmpresa.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblNombreEmpresa.Location = new System.Drawing.Point(22, 34);
            this.lblNombreEmpresa.Name = "lblNombreEmpresa";
            this.lblNombreEmpresa.Text = "Nombre de la empresa";
            this.txtNombreEmpresa.Font = new System.Drawing.Font("Segoe UI", 10F);
            this.txtNombreEmpresa.Location = new System.Drawing.Point(25, 54);
            this.txtNombreEmpresa.MaxLength = 150;
            this.txtNombreEmpresa.Name = "txtNombreEmpresa";
            this.txtNombreEmpresa.Size = new System.Drawing.Size(674, 25);
            this.lblLogo.AutoSize = true;
            this.lblLogo.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblLogo.Location = new System.Drawing.Point(22, 91);
            this.lblLogo.Name = "lblLogo";
            this.lblLogo.Text = "Logotipo";
            this.txtRutaLogo.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtRutaLogo.Location = new System.Drawing.Point(25, 111);
            this.txtRutaLogo.MaxLength = 500;
            this.txtRutaLogo.Name = "txtRutaLogo";
            this.txtRutaLogo.ReadOnly = true;
            this.txtRutaLogo.Size = new System.Drawing.Size(555, 23);
            this.btnExaminar.Location = new System.Drawing.Point(592, 109);
            this.btnExaminar.Name = "btnExaminar";
            this.btnExaminar.Size = new System.Drawing.Size(107, 28);
            this.btnExaminar.Text = "Examinar...";
            this.btnExaminar.UseVisualStyleBackColor = true;
            this.btnExaminar.Click += new System.EventHandler(this.btnExaminar_Click);
            this.lblInformacion.AutoSize = true;
            this.lblInformacion.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.lblInformacion.Location = new System.Drawing.Point(22, 148);
            this.lblInformacion.Name = "lblInformacion";
            this.lblInformacion.Text = "Información general";
            this.txtInformacionGeneral.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.txtInformacionGeneral.Location = new System.Drawing.Point(25, 168);
            this.txtInformacionGeneral.MaxLength = 500;
            this.txtInformacionGeneral.Multiline = true;
            this.txtInformacionGeneral.Name = "txtInformacionGeneral";
            this.txtInformacionGeneral.Size = new System.Drawing.Size(674, 54);
            this.pnlAdministrador.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.pnlAdministrador.Controls.Add(this.txtConfirmarContrasena);
            this.pnlAdministrador.Controls.Add(this.lblConfirmarContrasena);
            this.pnlAdministrador.Controls.Add(this.txtContrasena);
            this.pnlAdministrador.Controls.Add(this.lblContrasena);
            this.pnlAdministrador.Controls.Add(this.txtUsuarioAdministrador);
            this.pnlAdministrador.Controls.Add(this.lblUsuarioAdministrador);
            this.pnlAdministrador.Controls.Add(this.txtNombreAdministrador);
            this.pnlAdministrador.Controls.Add(this.lblNombreAdministrador);
            this.pnlAdministrador.Controls.Add(this.lblEstadoAdministrador);
            this.pnlAdministrador.Controls.Add(this.lblAdministrador);
            this.pnlAdministrador.Location = new System.Drawing.Point(41, 370);
            this.pnlAdministrador.Name = "pnlAdministrador";
            this.pnlAdministrador.Size = new System.Drawing.Size(728, 237);
            this.lblAdministrador.AutoSize = true;
            this.lblAdministrador.Font = new System.Drawing.Font("Segoe UI Semibold", 11F, System.Drawing.FontStyle.Bold);
            this.lblAdministrador.ForeColor = System.Drawing.Color.FromArgb(11, 55, 104);
            this.lblAdministrador.Location = new System.Drawing.Point(22, 16);
            this.lblAdministrador.Name = "lblAdministrador";
            this.lblAdministrador.Text = "Primer administrador";
            this.lblEstadoAdministrador.AutoSize = true;
            this.lblEstadoAdministrador.Font = new System.Drawing.Font("Segoe UI", 8.5F);
            this.lblEstadoAdministrador.ForeColor = System.Drawing.Color.FromArgb(91, 108, 128);
            this.lblEstadoAdministrador.Location = new System.Drawing.Point(22, 43);
            this.lblEstadoAdministrador.Name = "lblEstadoAdministrador";
            this.lblEstadoAdministrador.Text = "Estado del administrador";
            this.lblNombreAdministrador.AutoSize = true;
            this.lblNombreAdministrador.Location = new System.Drawing.Point(22, 76);
            this.lblNombreAdministrador.Name = "lblNombreAdministrador";
            this.lblNombreAdministrador.Text = "Nombre completo";
            this.txtNombreAdministrador.Location = new System.Drawing.Point(25, 96);
            this.txtNombreAdministrador.MaxLength = 150;
            this.txtNombreAdministrador.Name = "txtNombreAdministrador";
            this.txtNombreAdministrador.Size = new System.Drawing.Size(320, 20);
            this.lblUsuarioAdministrador.AutoSize = true;
            this.lblUsuarioAdministrador.Location = new System.Drawing.Point(371, 76);
            this.lblUsuarioAdministrador.Name = "lblUsuarioAdministrador";
            this.lblUsuarioAdministrador.Text = "Usuario";
            this.txtUsuarioAdministrador.Location = new System.Drawing.Point(374, 96);
            this.txtUsuarioAdministrador.MaxLength = 50;
            this.txtUsuarioAdministrador.Name = "txtUsuarioAdministrador";
            this.txtUsuarioAdministrador.Size = new System.Drawing.Size(325, 20);
            this.txtUsuarioAdministrador.KeyPress += new System.Windows.Forms.KeyPressEventHandler(this.txtUsuarioAdministrador_KeyPress);
            this.lblContrasena.AutoSize = true;
            this.lblContrasena.Location = new System.Drawing.Point(22, 139);
            this.lblContrasena.Name = "lblContrasena";
            this.lblContrasena.Text = "Contraseña";
            this.txtContrasena.Location = new System.Drawing.Point(25, 159);
            this.txtContrasena.MaxLength = 100;
            this.txtContrasena.Name = "txtContrasena";
            this.txtContrasena.PasswordChar = '●';
            this.txtContrasena.Size = new System.Drawing.Size(320, 20);
            this.lblConfirmarContrasena.AutoSize = true;
            this.lblConfirmarContrasena.Location = new System.Drawing.Point(371, 139);
            this.lblConfirmarContrasena.Name = "lblConfirmarContrasena";
            this.lblConfirmarContrasena.Text = "Confirmar contraseña";
            this.txtConfirmarContrasena.Location = new System.Drawing.Point(374, 159);
            this.txtConfirmarContrasena.MaxLength = 100;
            this.txtConfirmarContrasena.Name = "txtConfirmarContrasena";
            this.txtConfirmarContrasena.PasswordChar = '●';
            this.txtConfirmarContrasena.Size = new System.Drawing.Size(325, 20);
            this.btnGuardar.BackColor = System.Drawing.Color.FromArgb(0, 105, 240);
            this.btnGuardar.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.btnGuardar.ForeColor = System.Drawing.Color.White;
            this.btnGuardar.Location = new System.Drawing.Point(535, 630);
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.Size = new System.Drawing.Size(144, 42);
            this.btnGuardar.Text = "Guardar configuración";
            this.btnGuardar.UseVisualStyleBackColor = false;
            this.btnGuardar.Click += new System.EventHandler(this.btnGuardar_Click);
            this.btnSalir.Location = new System.Drawing.Point(685, 630);
            this.btnSalir.Name = "btnSalir";
            this.btnSalir.Size = new System.Drawing.Size(84, 42);
            this.btnSalir.Text = "Salir";
            this.btnSalir.UseVisualStyleBackColor = true;
            this.btnSalir.Click += new System.EventHandler(this.btnSalir_Click);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(810, 700);
            this.Controls.Add(this.btnSalir);
            this.Controls.Add(this.btnGuardar);
            this.Controls.Add(this.pnlAdministrador);
            this.Controls.Add(this.grpEmpresa);
            this.Controls.Add(this.lblSubtitulo);
            this.Controls.Add(this.lblTitulo);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.FixedSingle;
            this.MaximizeBox = false;
            this.MinimizeBox = false;
            this.Name = "frmConfiguracionInicial";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Configuración inicial";
            this.Load += new System.EventHandler(this.frmConfiguracionInicial_Load);
            this.grpEmpresa.ResumeLayout(false);
            this.grpEmpresa.PerformLayout();
            this.pnlAdministrador.ResumeLayout(false);
            this.pnlAdministrador.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();
        }

        private System.Windows.Forms.Label lblTitulo;
        private System.Windows.Forms.Label lblSubtitulo;
        private System.Windows.Forms.GroupBox grpEmpresa;
        private System.Windows.Forms.Label lblNombreEmpresa;
        private System.Windows.Forms.TextBox txtNombreEmpresa;
        private System.Windows.Forms.Label lblLogo;
        private System.Windows.Forms.TextBox txtRutaLogo;
        private System.Windows.Forms.Button btnExaminar;
        private System.Windows.Forms.Label lblInformacion;
        private System.Windows.Forms.TextBox txtInformacionGeneral;
        private System.Windows.Forms.Panel pnlAdministrador;
        private System.Windows.Forms.Label lblAdministrador;
        private System.Windows.Forms.Label lblEstadoAdministrador;
        private System.Windows.Forms.Label lblNombreAdministrador;
        private System.Windows.Forms.TextBox txtNombreAdministrador;
        private System.Windows.Forms.Label lblUsuarioAdministrador;
        private System.Windows.Forms.TextBox txtUsuarioAdministrador;
        private System.Windows.Forms.Label lblContrasena;
        private System.Windows.Forms.TextBox txtContrasena;
        private System.Windows.Forms.Label lblConfirmarContrasena;
        private System.Windows.Forms.TextBox txtConfirmarContrasena;
        private System.Windows.Forms.Button btnGuardar;
        private System.Windows.Forms.Button btnSalir;
    }
}
