USE DbSyncore;
GO

SET DATEFORMAT ymd;
GO

INSERT INTO TbTipoUsuario (Nombre, Descripcion) VALUES (N'Gestor', N'Usuario que administra y supervisa proyectos.');
INSERT INTO TbTipoUsuario (Nombre, Descripcion) VALUES (N'Colaborador', N'Usuario que ejecuta tareas asignadas.');
GO

INSERT INTO TbArea (Nombre, Activo) VALUES (N'Dirección', 1);
INSERT INTO TbArea (Nombre, Activo) VALUES (N'Tecnología', 1);
INSERT INTO TbArea (Nombre, Activo) VALUES (N'Mercadeo', 1);
INSERT INTO TbArea (Nombre, Activo) VALUES (N'Operaciones', 1);
INSERT INTO TbArea (Nombre, Activo) VALUES (N'Social', 1);
INSERT INTO TbArea (Nombre, Activo) VALUES (N'Recursos Humanos', 1);
INSERT INTO TbArea (Nombre, Activo) VALUES (N'Planificación', 1);
INSERT INTO TbArea (Nombre, Activo) VALUES (N'Logística', 1);
INSERT INTO TbArea (Nombre, Activo) VALUES (N'Administración', 1);
INSERT INTO TbArea (Nombre, Activo) VALUES (N'Calidad', 1);
INSERT INTO TbArea (Nombre, Activo) VALUES (N'Jurídica', 1);
INSERT INTO TbArea (Nombre, Activo) VALUES (N'Finanzas', 1);
GO

INSERT INTO TbTipoProyecto (Nombre, Activo) VALUES (N'Desarrollo de software', 1);
INSERT INTO TbTipoProyecto (Nombre, Activo) VALUES (N'Infraestructura', 1);
INSERT INTO TbTipoProyecto (Nombre, Activo) VALUES (N'Mejora continua', 1);
INSERT INTO TbTipoProyecto (Nombre, Activo) VALUES (N'Transformación digital', 1);
INSERT INTO TbTipoProyecto (Nombre, Activo) VALUES (N'Cumplimiento', 1);
GO

INSERT INTO TbRolProyecto (Nombre, Descripcion, Activo) VALUES (N'Coordinador', N'Coordina actividades dentro del proyecto.', 1);
INSERT INTO TbRolProyecto (Nombre, Descripcion, Activo) VALUES (N'Subcoordinador', N'Apoya la coordinación del proyecto.', 1);
GO

INSERT INTO TbPrioridad (Nombre, Activo) VALUES ('Alta', 1);
INSERT INTO TbPrioridad (Nombre, Activo) VALUES ('Media', 1);
INSERT INTO TbPrioridad (Nombre, Activo) VALUES ('Normal', 1);
GO

INSERT INTO TbEstadoProyecto (Nombre, Activo) VALUES (N'Activo', 1);
INSERT INTO TbEstadoProyecto (Nombre, Activo) VALUES (N'Observación', 1);
INSERT INTO TbEstadoProyecto (Nombre, Activo) VALUES (N'Crítico', 1);
INSERT INTO TbEstadoProyecto (Nombre, Activo) VALUES (N'Cerrado', 1);
GO

INSERT INTO TbEstadoHito (Nombre, Activo) VALUES (N'Planificado', 1);
INSERT INTO TbEstadoHito (Nombre, Activo) VALUES (N'Pendiente', 1);
INSERT INTO TbEstadoHito (Nombre, Activo) VALUES (N'En proceso', 1);
INSERT INTO TbEstadoHito (Nombre, Activo) VALUES (N'Cumplido', 1);
GO

INSERT INTO TbEstadoTarea (Nombre, Activo) VALUES (N'Pendiente', 1);
INSERT INTO TbEstadoTarea (Nombre, Activo) VALUES (N'En progreso', 1);
INSERT INTO TbEstadoTarea (Nombre, Activo) VALUES (N'En revisión', 1);
INSERT INTO TbEstadoTarea (Nombre, Activo) VALUES (N'Devuelta', 1);
INSERT INTO TbEstadoTarea (Nombre, Activo) VALUES (N'Vencida', 1);
INSERT INTO TbEstadoTarea (Nombre, Activo) VALUES (N'Completada', 1);
GO

INSERT INTO TbEstadoRevision (Nombre, Activo) VALUES (N'Pendiente', 1);
INSERT INTO TbEstadoRevision (Nombre, Activo) VALUES (N'Aprobada', 1);
INSERT INTO TbEstadoRevision (Nombre, Activo) VALUES (N'Corrección solicitada', 1);
GO

INSERT INTO TbTipoNotificacion (Nombre, Activo) VALUES (N'Tarea vencida', 1);
INSERT INTO TbTipoNotificacion (Nombre, Activo) VALUES (N'Tarea devuelta', 1);
INSERT INTO TbTipoNotificacion (Nombre, Activo) VALUES (N'Nueva tarea', 1);
INSERT INTO TbTipoNotificacion (Nombre, Activo) VALUES (N'Alerta proyecto', 1);
INSERT INTO TbTipoNotificacion (Nombre, Activo) VALUES (N'Recordatorio', 1);
GO

INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('gperez', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Gabriela Pérez', 1, 1, 1, '2026-01-05T08:00:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('lcastro', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Luis Castro', 1, 7, 1, '2026-01-05T08:05:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('mlopez', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'María López', 1, 9, 1, '2026-01-05T08:10:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('rquintanilla', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Roberto Quintanilla', 1, 2, 1, '2026-01-05T08:15:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('sramirez', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Sofía Ramírez', 1, 1, 1, '2026-01-05T08:20:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('amartinez', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Ana Martínez', 2, 2, 1, '2026-01-06T08:00:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('aortiz', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Andrea Ortiz', 2, 3, 1, '2026-01-06T08:05:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('chernandez', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Carlos Hernández', 2, 4, 1, '2026-01-06T08:10:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('cmejia', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Claudia Mejía', 2, 5, 1, '2026-01-06T08:15:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('dromero', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Daniel Romero', 2, 6, 1, '2026-01-06T08:20:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('egarcia', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Elena García', 2, 7, 1, '2026-01-06T08:25:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('fmunoz', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Fernando Muñoz', 2, 8, 1, '2026-01-06T08:30:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('jramirez', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'José Ramírez', 2, 9, 1, '2026-01-06T08:35:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('mrivera', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Miguel Rivera', 2, 10, 1, '2026-01-06T08:40:00');
INSERT INTO TbUsuario (NombreUsuario, Contrasena, NombreCompleto, IdTipoUsuario, IdArea, Activo, FechaCreacion) VALUES ('ptorres', '$2a$10$ZuSFBul0la80ZfjFCO3fdOqER2ej.9HtTsumakzlvgDt/3oY7Xjja', N'Patricia Torres', 2, 11, 1, '2026-01-06T08:45:00');
GO

INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-001', N'Migración a nube institucional', N'Migrar los servicios institucionales a una infraestructura de nube controlada.', N'Reducir riesgos de disponibilidad y mejorar la capacidad de recuperación.', N'Aplicaciones internas, bases de datos y respaldos institucionales.', N'Servicios principales operando en la nueva infraestructura.', N'Proyecto prioritario con dependencias técnicas.', 2, 4, 1, 1, 3, '2026-06-01', '2026-10-31', NULL, 70, '2026-05-20T08:00:00', '2026-08-26T15:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-002', N'Automatización de mesa de ayuda', N'Automatizar el registro y seguimiento de solicitudes internas.', N'Reducir tiempos de atención y mejorar la trazabilidad.', N'Incidentes, solicitudes y reportes de atención.', N'Flujo digital de mesa de ayuda funcionando.', NULL, 2, 1, 1, 1, 1, '2026-06-15', '2026-11-15', NULL, 60, '2026-06-01T08:00:00', '2026-08-25T14:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-003', N'Actualización de contratos', N'Actualizar los contratos institucionales vigentes.', N'Alinear documentación con requerimientos actuales.', N'Contratos de proveedores y servicios recurrentes.', N'Contratos revisados y actualizados.', N'Pendiente validación de documentos legales.', 11, 5, 1, 2, 2, '2026-05-01', '2026-09-30', NULL, 75, '2026-04-20T08:00:00', '2026-08-20T11:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-004', N'Campaña institucional', N'Fortalecer la comunicación institucional.', N'Mejorar el alcance de las comunicaciones internas y externas.', N'Campaña digital y materiales institucionales.', N'Campaña publicada y métricas disponibles.', NULL, 3, 3, 1, 2, 1, '2026-07-01', '2026-10-15', NULL, 50, '2026-06-20T08:00:00', '2026-08-24T09:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-005', N'Depuración de datos maestros', N'Depurar registros inconsistentes en catálogos principales.', N'Mejorar la calidad de información institucional.', N'Clientes, proveedores y catálogos internos.', N'Datos duplicados e inconsistentes corregidos.', N'Se identificaron registros con información incompleta.', 10, 3, 1, 1, 3, '2026-06-10', '2026-09-30', NULL, 65, '2026-06-01T08:00:00', '2026-08-27T13:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-006', N'Cierre financiero anual', N'Preparar las actividades del cierre financiero.', N'Cumplir fechas y controles internos.', N'Conciliaciones, ajustes y reportes de cierre.', N'Cierre financiero ejecutado en fecha.', NULL, 12, 5, 1, 1, 1, '2026-07-15', '2026-12-20', NULL, 40, '2026-07-01T08:00:00', '2026-08-21T10:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-007', N'Portal de indicadores', N'Crear un portal interno para indicadores de gestión.', N'Centralizar métricas y reducir reportes manuales.', N'Indicadores de proyectos y productividad.', N'Portal disponible para gestores.', NULL, 7, 1, 1, 2, 1, '2026-08-01', '2026-12-15', NULL, 30, '2026-07-20T08:00:00', '2026-08-28T08:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-008', N'Renovación de infraestructura', N'Renovar equipos y componentes de infraestructura tecnológica.', N'Reducir fallas por obsolescencia.', N'Servidores, red y equipos críticos.', N'Infraestructura renovada y documentada.', N'Entrega de algunos equipos retrasada.', 2, 2, 1, 1, 2, '2026-05-15', '2026-10-31', NULL, 55, '2026-05-01T08:00:00', '2026-08-19T16:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-009', N'Programa de capacitación', N'Ejecutar un programa de capacitación interna.', N'Fortalecer competencias del personal.', N'Personal administrativo y operativo.', N'Plan de capacitación completado.', NULL, 6, 3, 2, 2, 1, '2026-07-01', '2026-11-30', NULL, 45, '2026-06-15T08:00:00', '2026-08-17T09:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-010', N'Digitalización de expedientes', N'Digitalizar expedientes administrativos.', N'Reducir dependencia de documentos físicos.', N'Expedientes administrativos activos.', N'Expedientes digitalizados e indexados.', NULL, 9, 4, 2, 2, 1, '2026-06-01', '2026-12-10', NULL, 50, '2026-05-15T08:00:00', '2026-08-22T11:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-011', N'Reorganización logística', N'Mejorar el flujo de materiales y entregas.', N'Reducir tiempos y movimientos innecesarios.', N'Almacén, despacho y rutas internas.', N'Proceso logístico actualizado.', NULL, 8, 3, 2, 3, 1, '2026-07-20', '2026-11-20', NULL, 35, '2026-07-05T08:00:00', '2026-08-23T14:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-012', N'Encuesta de clima laboral', N'Medir el clima laboral institucional.', N'Identificar oportunidades de mejora.', N'Todo el personal.', N'Informe de resultados y plan de acción.', N'Proyecto finalizado.', 6, 3, 3, 3, 4, '2026-02-01', '2026-06-30', '2026-06-28', 100, '2026-01-20T08:00:00', '2026-06-28T17:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-013', N'Sistema de control de calidad', N'Desarrollar un sistema para registrar controles de calidad.', N'Mejorar seguimiento de hallazgos y correcciones.', N'Procesos de control y seguimiento.', N'Sistema implementado en producción.', N'Retraso en pruebas funcionales.', 10, 1, 3, 1, 3, '2026-06-20', '2026-11-30', NULL, 55, '2026-06-01T08:00:00', '2026-08-28T12:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-014', N'Gestión documental legal', N'Organizar la documentación legal institucional.', N'Mejorar disponibilidad y control documental.', N'Contratos, poderes y documentación jurídica.', N'Repositorio documental organizado.', NULL, 11, 5, 4, 2, 1, '2026-07-10', '2026-12-05', NULL, 40, '2026-06-25T08:00:00', '2026-08-25T10:00:00');
INSERT INTO TbProyecto (Codigo, Nombre, Objetivo, Justificacion, Alcance, ResultadoEsperado, Observacion, IdArea, IdTipoProyecto, IdResponsable, IdPrioridad, IdEstadoProyecto, FechaInicio, FechaCierreEstimada, FechaCierreReal, AvancePlanificado, FechaCreacion, UltimaModificacion) VALUES ('PRY-015', N'Optimización de procesos sociales', N'Optimizar actividades y controles del área social.', N'Reducir tiempos de respuesta y reprocesos.', N'Procesos internos del área social.', N'Procedimientos actualizados y medidos.', NULL, 5, 3, 4, 3, 1, '2026-08-01', '2026-12-20', NULL, 25, '2026-07-20T08:00:00', '2026-08-26T09:00:00');
GO

INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (1, 6, 1, '2026-06-01T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (1, 7, 2, '2026-06-01T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (1, 8, 2, '2026-06-01T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (1, 14, 2, '2026-06-01T08:15:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (2, 6, 1, '2026-06-15T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (2, 7, 2, '2026-06-15T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (2, 8, 2, '2026-06-15T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (3, 6, 1, '2026-05-01T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (3, 15, 2, '2026-05-01T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (3, 9, 2, '2026-05-01T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (4, 6, 1, '2026-07-01T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (4, 7, 2, '2026-07-01T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (4, 9, 2, '2026-07-01T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (5, 6, 1, '2026-06-10T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (5, 8, 2, '2026-06-10T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (5, 14, 2, '2026-06-10T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (6, 6, 1, '2026-07-15T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (6, 9, 2, '2026-07-15T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (6, 10, 2, '2026-07-15T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (7, 6, 1, '2026-08-01T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (7, 7, 2, '2026-08-01T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (7, 11, 2, '2026-08-01T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (8, 6, 1, '2026-05-15T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (8, 8, 2, '2026-05-15T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (8, 12, 2, '2026-05-15T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (9, 10, 1, '2026-07-01T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (9, 11, 2, '2026-07-01T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (9, 13, 2, '2026-07-01T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (10, 13, 1, '2026-06-01T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (10, 11, 2, '2026-06-01T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (10, 15, 2, '2026-06-01T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (11, 12, 1, '2026-07-20T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (11, 8, 2, '2026-07-20T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (11, 14, 2, '2026-07-20T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (12, 10, 1, '2026-02-01T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (12, 9, 2, '2026-02-01T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (13, 14, 1, '2026-06-20T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (13, 6, 2, '2026-06-20T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (13, 8, 2, '2026-06-20T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (14, 15, 1, '2026-07-10T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (14, 13, 2, '2026-07-10T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (14, 11, 2, '2026-07-10T08:10:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (15, 9, 1, '2026-08-01T08:00:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (15, 10, 2, '2026-08-01T08:05:00', 1);
INSERT INTO TbEquipoProyecto (IdProyecto, IdUsuario, IdRolProyecto, FechaAsignacion, Activo) VALUES (15, 7, 2, '2026-08-01T08:10:00', 1);
GO

INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (1, N'Infraestructura base disponible', N'Preparar recursos iniciales de nube.', '2026-07-15', 6, 4, '2026-07-14');
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (1, N'Migración de servicios críticos', N'Migrar los servicios principales.', '2026-09-15', 6, 3, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (2, N'Flujo de tickets definido', N'Definir estados y reglas de atención.', '2026-07-20', 7, 4, '2026-07-19');
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (2, N'Módulo de reportes', N'Completar reportes de atención.', '2026-09-25', 6, 3, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (3, N'Inventario contractual', N'Consolidar contratos vigentes.', '2026-06-15', 15, 4, '2026-06-14');
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (3, N'Validación jurídica final', N'Finalizar la validación de cambios.', '2026-09-10', 15, 2, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (4, N'Diseño de campaña', N'Aprobar piezas principales.', '2026-08-10', 7, 4, '2026-08-09');
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (4, N'Lanzamiento de campaña', N'Publicar campaña institucional.', '2026-09-05', 9, 3, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (5, N'Reglas de calidad definidas', N'Definir criterios de depuración.', '2026-07-01', 14, 4, '2026-06-30');
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (5, N'Depuración final', N'Completar depuración de registros.', '2026-09-15', 6, 3, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (6, N'Conciliaciones preliminares', N'Preparar conciliaciones base.', '2026-09-20', 10, 3, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (6, N'Cierre preliminar', N'Ejecutar cierre de prueba.', '2026-11-30', 6, 1, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (7, N'Prototipo de indicadores', N'Disponer del primer prototipo.', '2026-09-10', 11, 3, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (7, N'Publicación del portal', N'Publicar versión inicial.', '2026-12-01', 6, 1, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (8, N'Inventario de equipos', N'Completar inventario físico.', '2026-06-30', 8, 4, '2026-06-28');
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (8, N'Reemplazo de equipos críticos', N'Instalar nuevos equipos.', '2026-09-30', 12, 3, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (9, N'Plan de formación', N'Definir contenidos y calendario.', '2026-08-15', 10, 4, '2026-08-14');
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (9, N'Segunda jornada', N'Ejecutar segunda jornada de capacitación.', '2026-10-15', 11, 1, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (10, N'Inventario de expedientes', N'Identificar expedientes activos.', '2026-07-20', 13, 4, '2026-07-18');
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (10, N'Digitalización al 75%', N'Alcanzar tres cuartas partes del universo.', '2026-10-31', 11, 3, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (11, N'Diagnóstico logístico', N'Documentar problemas actuales.', '2026-08-20', 12, 4, '2026-08-18');
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (11, N'Prueba de nuevo flujo', N'Validar proceso reorganizado.', '2026-10-20', 8, 1, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (12, N'Encuesta aplicada', N'Completar aplicación de encuesta.', '2026-05-15', 9, 4, '2026-05-14');
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (12, N'Informe final', N'Presentar resultados finales.', '2026-06-25', 10, 4, '2026-06-24');
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (13, N'Módulo de hallazgos', N'Completar registro de hallazgos.', '2026-09-15', 14, 3, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (13, N'Pruebas de usuario', N'Ejecutar pruebas funcionales.', '2026-10-30', 6, 1, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (14, N'Clasificación documental', N'Definir categorías legales.', '2026-09-05', 15, 3, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (14, N'Repositorio final', N'Completar carga documental.', '2026-11-20', 13, 1, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (15, N'Mapeo de procesos', N'Documentar procesos actuales.', '2026-09-20', 9, 3, NULL);
INSERT INTO TbHito (IdProyecto, Nombre, Descripcion, FechaObjetivo, IdResponsable, IdEstadoHito, FechaCumplimiento) VALUES (15, N'Procedimientos actualizados', N'Publicar procedimientos optimizados.', '2026-12-05', 10, 1, NULL);
GO

INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (1, 2, N'Configurar ambiente de nube', N'Configurar recursos, redes y permisos del ambiente productivo.', N'Requiere validación de seguridad.', 6, 1, 1, 3, '2026-07-01', '2026-08-28', 100, '2026-07-01T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (1, 1, N'Crear inventario de servidores', N'Identificar servidores y servicios a migrar.', NULL, 7, 1, 2, 6, '2026-06-01', '2026-06-30', 100, '2026-06-01T08:05:00', '2026-06-28T16:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (1, 2, N'Migrar base de datos principal', N'Migrar la base de datos principal al nuevo ambiente.', N'Pendiente ventana de mantenimiento.', 8, 1, 1, 5, '2026-07-15', '2026-08-20', 40, '2026-07-15T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (1, 2, N'Validar respaldos en nube', N'Validar recuperación de respaldos migrados.', NULL, 6, 1, 2, 2, '2026-08-01', '2026-09-10', 65, '2026-08-01T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (2, 3, N'Definir catálogo de solicitudes', N'Definir tipos de solicitudes y categorías.', NULL, 6, 1, 2, 6, '2026-06-15', '2026-07-15', 100, '2026-06-15T08:00:00', '2026-07-14T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (2, 4, N'Construir módulo de reportes', N'Desarrollar consultas y reportes operativos.', N'Pendiente revisión funcional.', 7, 1, 1, 3, '2026-07-20', '2026-08-29', 100, '2026-07-20T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (2, 4, N'Configurar notificaciones de tickets', N'Configurar alertas y recordatorios automáticos.', NULL, 8, 1, 2, 2, '2026-08-01', '2026-09-20', 55, '2026-08-01T08:10:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (2, 4, N'Documentar flujo de soporte', N'Documentar el uso del nuevo flujo.', NULL, 6, 1, 3, 1, '2026-09-01', '2026-10-15', 0, '2026-08-20T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (3, 5, N'Consolidar contratos vigentes', N'Reunir contratos y anexos vigentes.', NULL, 15, 1, 1, 6, '2026-05-01', '2026-06-10', 100, '2026-05-01T08:00:00', '2026-06-08T16:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (3, 6, N'Revisar cláusulas de renovación', N'Revisar cláusulas de renovación y terminación.', N'Faltan dos anexos.', 6, 1, 1, 5, '2026-07-01', '2026-08-15', 45, '2026-07-01T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (3, 6, N'Validar cambios con áreas', N'Validar cambios contractuales con áreas responsables.', NULL, 9, 1, 2, 2, '2026-08-01', '2026-09-05', 60, '2026-08-01T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (3, 6, N'Preparar versiones finales', N'Preparar documentos finales para firma.', NULL, 15, 1, 2, 1, '2026-09-01', '2026-09-25', 0, '2026-08-25T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (4, 7, N'Diseñar piezas principales', N'Diseñar piezas para campaña institucional.', NULL, 7, 1, 2, 6, '2026-07-01', '2026-08-05', 100, '2026-07-01T08:00:00', '2026-08-04T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (4, 8, N'Programar publicaciones', N'Programar publicaciones para canales institucionales.', NULL, 9, 1, 2, 2, '2026-08-10', '2026-09-03', 70, '2026-08-10T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (4, 8, N'Revisar métricas iniciales', N'Revisar resultados de primeras publicaciones.', NULL, 6, 1, 3, 1, '2026-09-06', '2026-09-20', 0, '2026-08-20T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (4, 8, N'Preparar informe de campaña', N'Preparar informe final de resultados.', NULL, 7, 1, 3, 1, '2026-09-20', '2026-10-10', 0, '2026-08-22T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (5, 9, N'Definir reglas de duplicados', N'Definir reglas para detectar registros duplicados.', NULL, 14, 1, 1, 6, '2026-06-10', '2026-06-30', 100, '2026-06-10T08:00:00', '2026-06-29T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (5, 10, N'Depurar clientes duplicados', N'Depurar registros duplicados de clientes.', N'Volumen mayor al estimado.', 6, 1, 1, 4, '2026-07-01', '2026-09-10', 75, '2026-07-01T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (5, 10, N'Depurar proveedores', N'Depurar registros de proveedores.', NULL, 8, 1, 2, 5, '2026-07-10', '2026-08-18', 35, '2026-07-10T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (5, 10, N'Validar catálogo final', N'Validar consistencia de catálogos depurados.', NULL, 14, 1, 2, 1, '2026-09-11', '2026-09-25', 0, '2026-08-25T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (6, 11, N'Preparar conciliaciones bancarias', N'Preparar conciliaciones de cuentas principales.', NULL, 10, 1, 1, 2, '2026-07-15', '2026-09-15', 60, '2026-07-15T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (6, 11, N'Revisar auxiliares contables', N'Revisar auxiliares y diferencias pendientes.', NULL, 6, 1, 2, 2, '2026-08-01', '2026-09-20', 50, '2026-08-01T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (6, 12, N'Preparar cierre de prueba', N'Ejecutar cierre preliminar.', NULL, 9, 1, 1, 1, '2026-10-01', '2026-11-25', 0, '2026-08-15T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (6, 12, N'Documentar ajustes finales', N'Documentar ajustes del cierre anual.', NULL, 10, 1, 3, 1, '2026-11-01', '2026-12-10', 0, '2026-08-18T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (7, 13, N'Definir indicadores del portal', N'Definir indicadores iniciales y fuentes.', NULL, 11, 1, 2, 2, '2026-08-01', '2026-09-05', 70, '2026-08-01T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (7, 13, N'Diseñar tablero principal', N'Diseñar tablero para gestores.', NULL, 6, 1, 2, 2, '2026-08-05', '2026-09-10', 50, '2026-08-05T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (7, 14, N'Desarrollar filtros del portal', N'Desarrollar filtros por proyecto y usuario.', NULL, 7, 1, 3, 1, '2026-09-10', '2026-10-20', 0, '2026-08-20T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (7, 14, N'Publicar versión inicial', N'Publicar primera versión del portal.', NULL, 11, 1, 1, 1, '2026-11-01', '2026-12-01', 0, '2026-08-20T08:05:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (8, 15, N'Levantar inventario físico', N'Levantar inventario de equipos críticos.', NULL, 8, 1, 2, 6, '2026-05-15', '2026-06-25', 100, '2026-05-15T08:00:00', '2026-06-24T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (8, 16, N'Instalar nuevos switches', N'Instalar y configurar switches principales.', N'Proveedor reprogramó entrega.', 12, 1, 1, 5, '2026-07-01', '2026-08-10', 30, '2026-07-01T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (8, 16, N'Reconfigurar red interna', N'Reconfigurar segmentos de red internos.', NULL, 6, 1, 1, 2, '2026-08-15', '2026-09-30', 55, '2026-08-15T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (8, 16, N'Documentar nueva topología', N'Documentar la topología final.', NULL, 8, 1, 3, 1, '2026-09-20', '2026-10-20', 0, '2026-08-25T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (9, 17, N'Definir temario', N'Definir temario del programa de formación.', NULL, 10, 2, 2, 6, '2026-07-01', '2026-08-10', 100, '2026-07-01T08:00:00', '2026-08-09T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (9, 18, N'Coordinar facilitadores', N'Coordinar facilitadores para jornadas.', NULL, 11, 2, 2, 2, '2026-08-15', '2026-09-30', 50, '2026-08-15T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (9, 18, N'Preparar materiales', N'Preparar materiales de capacitación.', NULL, 13, 2, 3, 2, '2026-08-20', '2026-10-10', 40, '2026-08-20T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (9, 18, N'Evaluar segunda jornada', N'Aplicar evaluación de la segunda jornada.', NULL, 10, 2, 3, 1, '2026-10-15', '2026-10-25', 0, '2026-08-25T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (10, 19, N'Clasificar expedientes', N'Clasificar expedientes por tipo y año.', NULL, 13, 2, 2, 6, '2026-06-01', '2026-07-15', 100, '2026-06-01T08:00:00', '2026-07-14T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (10, 20, N'Escanear expedientes activos', N'Escanear documentación activa.', NULL, 11, 2, 2, 2, '2026-07-20', '2026-10-15', 65, '2026-07-20T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (10, 20, N'Revisar nomenclatura documental', N'Revisar nombres y metadatos de archivos.', NULL, 15, 2, 3, 2, '2026-08-01', '2026-09-30', 55, '2026-08-01T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (10, 20, N'Publicar repositorio', N'Publicar repositorio final de expedientes.', NULL, 13, 2, 1, 1, '2026-11-01', '2026-12-05', 0, '2026-08-25T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (11, 21, N'Mapear rutas actuales', N'Mapear rutas y movimientos actuales.', NULL, 12, 2, 2, 6, '2026-07-20', '2026-08-15', 100, '2026-07-20T08:00:00', '2026-08-14T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (11, 22, N'Diseñar nuevo flujo', N'Diseñar flujo optimizado de despacho.', NULL, 8, 2, 2, 2, '2026-08-20', '2026-09-25', 45, '2026-08-20T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (11, 22, N'Preparar señalización', N'Preparar señalización de nuevas rutas.', NULL, 14, 2, 3, 1, '2026-09-15', '2026-10-10', 0, '2026-08-23T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (11, 22, N'Evaluar prueba piloto', N'Evaluar resultados de prueba piloto.', NULL, 12, 2, 3, 1, '2026-10-20', '2026-11-05', 0, '2026-08-25T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (12, 23, N'Diseñar encuesta', N'Diseñar instrumento de clima laboral.', NULL, 9, 3, 2, 6, '2026-02-01', '2026-03-15', 100, '2026-02-01T08:00:00', '2026-03-14T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (12, 23, N'Aplicar encuesta', N'Aplicar encuesta a todo el personal.', NULL, 10, 3, 2, 6, '2026-04-01', '2026-05-15', 100, '2026-04-01T08:00:00', '2026-05-14T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (12, 24, N'Analizar resultados', N'Analizar resultados obtenidos.', NULL, 9, 3, 2, 6, '2026-05-16', '2026-06-15', 100, '2026-05-16T08:00:00', '2026-06-14T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (12, 24, N'Presentar informe final', N'Presentar informe y plan de acción.', NULL, 10, 3, 1, 6, '2026-06-16', '2026-06-25', 100, '2026-06-16T08:00:00', '2026-06-24T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (13, 25, N'Diseñar catálogo de hallazgos', N'Definir catálogo de tipos de hallazgo.', NULL, 14, 3, 1, 6, '2026-06-20', '2026-07-25', 100, '2026-06-20T08:00:00', '2026-07-24T15:00:00');
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (13, 25, N'Desarrollar registro de controles', N'Desarrollar formulario de controles de calidad.', NULL, 6, 3, 1, 2, '2026-07-15', '2026-09-15', 65, '2026-07-15T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (13, 26, N'Preparar casos de prueba', N'Preparar casos para pruebas funcionales.', NULL, 8, 3, 2, 2, '2026-08-15', '2026-10-15', 40, '2026-08-15T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (13, 26, N'Ejecutar pruebas de usuario', N'Ejecutar pruebas con usuarios finales.', NULL, 14, 3, 1, 1, '2026-10-01', '2026-10-30', 0, '2026-08-25T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (14, 27, N'Definir clasificación legal', N'Definir estructura de clasificación documental.', NULL, 15, 4, 2, 2, '2026-07-10', '2026-09-05', 75, '2026-07-10T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (14, 27, N'Preparar metadatos', N'Definir metadatos de documentos legales.', NULL, 13, 4, 3, 2, '2026-08-01', '2026-09-20', 50, '2026-08-01T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (14, 28, N'Cargar documentos históricos', N'Cargar documentos legales históricos.', NULL, 11, 4, 2, 1, '2026-09-15', '2026-11-10', 0, '2026-08-25T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (14, 28, N'Validar repositorio', N'Validar permisos y búsquedas del repositorio.', NULL, 15, 4, 1, 1, '2026-11-01', '2026-11-25', 0, '2026-08-25T08:05:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (15, 29, N'Documentar procesos actuales', N'Documentar procesos del área social.', NULL, 9, 4, 3, 2, '2026-08-01', '2026-09-15', 60, '2026-08-01T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (15, 29, N'Identificar reprocesos', N'Identificar puntos de reproceso.', NULL, 10, 4, 3, 2, '2026-08-10', '2026-09-20', 40, '2026-08-10T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (15, 30, N'Redactar procedimientos nuevos', N'Redactar procedimientos optimizados.', NULL, 7, 4, 2, 1, '2026-09-15', '2026-11-15', 0, '2026-08-25T08:00:00', NULL);
INSERT INTO TbTarea (IdProyecto, IdHito, Nombre, Descripcion, Observacion, IdResponsable, IdCreador, IdPrioridad, IdEstadoTarea, FechaInicio, FechaLimite, AvanceActual, FechaCreacion, FechaCompletada) VALUES (15, 30, N'Publicar procedimientos', N'Publicar procedimientos aprobados.', NULL, 9, 4, 3, 1, '2026-11-20', '2026-12-10', 0, '2026-08-25T08:05:00', NULL);
GO

INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (1, 6, 40, '2026-08-10', N'Se configuraron redes y grupos de recursos.', N'Pendiente validación de permisos.', N'Completar seguridad y pruebas.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (1, 6, 100, '2026-08-28', N'Configuración completada y lista para revisión.', N'Sin dificultades pendientes.', N'Esperar revisión del gestor.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (2, 7, 100, '2026-06-28', N'Inventario de servidores completado.', NULL, N'Usar inventario para planificación de migración.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (3, 8, 40, '2026-08-18', N'Migración parcial ejecutada.', N'No se obtuvo ventana completa de mantenimiento.', N'Reprogramar migración restante.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (4, 6, 65, '2026-08-25', N'Se validaron respaldos principales.', NULL, N'Completar pruebas de restauración.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (5, 6, 100, '2026-07-14', N'Catálogo final validado.', NULL, N'Continuar con configuración del flujo.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (6, 7, 100, '2026-08-29', N'Módulo de reportes terminado y enviado a revisión.', NULL, N'Esperar revisión funcional.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (7, 8, 55, '2026-08-24', N'Se configuraron notificaciones principales.', N'Falta revisar mensajes de recordatorio.', N'Completar reglas restantes.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (9, 15, 100, '2026-06-08', N'Contratos consolidados.', NULL, N'Iniciar revisión de cláusulas.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (10, 6, 45, '2026-08-12', N'Se revisó casi la mitad de las cláusulas.', N'Faltan anexos de dos contratos.', N'Solicitar anexos y continuar.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (11, 9, 60, '2026-08-24', N'Validación realizada con varias áreas.', NULL, N'Completar validaciones restantes.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (13, 7, 100, '2026-08-04', N'Piezas aprobadas.', NULL, N'Programar publicaciones.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (14, 9, 70, '2026-08-27', N'Publicaciones programadas para primera etapa.', NULL, N'Completar segunda etapa.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (17, 14, 100, '2026-06-29', N'Reglas de duplicados definidas.', NULL, N'Aplicar reglas al universo.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (18, 6, 75, '2026-08-27', N'Se depuró la mayor parte de clientes.', N'Hay registros con información incompleta.', N'Completar validación manual.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (19, 8, 35, '2026-08-17', N'Se inició depuración de proveedores.', N'Cantidad de duplicados mayor a la prevista.', N'Reprogramar carga de trabajo.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (21, 10, 60, '2026-08-26', N'Conciliaciones principales avanzadas.', NULL, N'Revisar diferencias pendientes.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (22, 6, 50, '2026-08-25', N'Revisión de auxiliares al 50%.', NULL, N'Completar auxiliares restantes.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (25, 11, 70, '2026-08-28', N'Indicadores principales definidos.', NULL, N'Validar fuentes de datos.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (26, 6, 50, '2026-08-27', N'Diseño del tablero a la mitad.', NULL, N'Completar componentes restantes.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (29, 8, 100, '2026-06-24', N'Inventario completado.', NULL, N'Programar sustituciones.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (30, 12, 30, '2026-08-09', N'Instalación parcial de switches.', N'Entrega pendiente del proveedor.', N'Reprogramar instalación.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (31, 6, 55, '2026-08-27', N'Reconfiguración de red avanzada.', NULL, N'Completar segmentos restantes.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (33, 10, 100, '2026-08-09', N'Temario completado.', NULL, N'Coordinar facilitadores.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (34, 11, 50, '2026-08-27', N'Facilitadores parcialmente confirmados.', NULL, N'Confirmar jornadas restantes.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (35, 13, 40, '2026-08-26', N'Materiales iniciales preparados.', NULL, N'Completar presentaciones.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (37, 13, 100, '2026-07-14', N'Expedientes clasificados.', NULL, N'Iniciar digitalización.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (38, 11, 65, '2026-08-28', N'Digitalización supera la mitad.', NULL, N'Continuar carga.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (39, 15, 55, '2026-08-27', N'Nomenclatura revisada parcialmente.', NULL, N'Completar revisión.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (41, 12, 100, '2026-08-14', N'Mapeo de rutas completado.', NULL, N'Diseñar nuevo flujo.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (42, 8, 45, '2026-08-28', N'Nuevo flujo en diseño.', NULL, N'Finalizar propuesta.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (45, 9, 100, '2026-03-14', N'Encuesta diseñada.', NULL, N'Preparar aplicación.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (46, 10, 100, '2026-05-14', N'Encuesta aplicada.', NULL, N'Analizar resultados.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (47, 9, 100, '2026-06-14', N'Análisis completado.', NULL, N'Preparar informe.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (48, 10, 100, '2026-06-24', N'Informe presentado.', NULL, N'Cierre del proyecto.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (49, 14, 100, '2026-07-24', N'Catálogo completado.', NULL, N'Desarrollar controles.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (50, 6, 65, '2026-08-27', N'Formulario principal desarrollado.', NULL, N'Completar validaciones.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (51, 8, 40, '2026-08-27', N'Casos principales definidos.', NULL, N'Completar escenarios restantes.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (53, 15, 75, '2026-08-28', N'Clasificación avanzada.', NULL, N'Validar categorías.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (54, 13, 50, '2026-08-27', N'Metadatos parcialmente definidos.', NULL, N'Completar campos.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (57, 9, 60, '2026-08-28', N'Procesos principales documentados.', NULL, N'Completar procesos secundarios.');
INSERT INTO TbAvance (IdTarea, IdUsuario, Porcentaje, FechaRegistro, Descripcion, Dificultad, ProximoPaso) VALUES (58, 10, 40, '2026-08-27', N'Reprocesos principales identificados.', NULL, N'Analizar causas.');
GO

INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (2, N'evidencia_nube.pdf', 'C:\Syncore\Evidencias\evidencia_nube.pdf', 'PDF', '2026-08-28T10:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (4, N'migracion_bd.xlsx', 'C:\Syncore\Evidencias\migracion_bd.xlsx', 'XLSX', '2026-08-18T11:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (7, N'reportes_finales.pdf', 'C:\Syncore\Evidencias\reportes_finales.pdf', 'PDF', '2026-08-29T09:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (10, N'revision_clausulas.docx', 'C:\Syncore\Evidencias\revision_clausulas.docx', 'DOCX', '2026-08-12T12:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (15, N'depuracion_clientes.xlsx', 'C:\Syncore\Evidencias\depuracion_clientes.xlsx', 'XLSX', '2026-08-27T15:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (17, N'conciliaciones.xlsx', 'C:\Syncore\Evidencias\conciliaciones.xlsx', 'XLSX', '2026-08-26T14:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (19, N'indicadores_portal.pdf', 'C:\Syncore\Evidencias\indicadores_portal.pdf', 'PDF', '2026-08-28T13:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (23, N'red_interna.png', 'C:\Syncore\Evidencias\red_interna.png', 'PNG', '2026-08-27T13:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (25, N'facilitadores.xlsx', 'C:\Syncore\Evidencias\facilitadores.xlsx', 'XLSX', '2026-08-27T14:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (28, N'avance_digitalizacion.pdf', 'C:\Syncore\Evidencias\avance_digitalizacion.pdf', 'PDF', '2026-08-28T11:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (31, N'flujo_logistico.pdf', 'C:\Syncore\Evidencias\flujo_logistico.pdf', 'PDF', '2026-08-28T10:30:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (37, N'control_calidad.png', 'C:\Syncore\Evidencias\control_calidad.png', 'PNG', '2026-08-27T10:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (39, N'clasificacion_legal.docx', 'C:\Syncore\Evidencias\clasificacion_legal.docx', 'DOCX', '2026-08-28T10:00:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (41, N'procesos_sociales.pdf', 'C:\Syncore\Evidencias\procesos_sociales.pdf', 'PDF', '2026-08-28T11:30:00');
INSERT INTO TbEvidencia (IdAvance, NombreArchivo, RutaArchivo, TipoArchivo, FechaSubida) VALUES (42, N'reprocesos.xlsx', 'C:\Syncore\Evidencias\reprocesos.xlsx', 'XLSX', '2026-08-27T16:00:00');
GO

INSERT INTO TbRevisionTarea (IdTarea, IdRevisor, FechaEnvio, FechaRevision, IdResultadoRevision, Comentario) VALUES (1, 1, '2026-08-28T10:05:00', NULL, 1, NULL);
INSERT INTO TbRevisionTarea (IdTarea, IdRevisor, FechaEnvio, FechaRevision, IdResultadoRevision, Comentario) VALUES (6, 1, '2026-08-29T09:05:00', NULL, 1, NULL);
INSERT INTO TbRevisionTarea (IdTarea, IdRevisor, FechaEnvio, FechaRevision, IdResultadoRevision, Comentario) VALUES (2, 1, '2026-06-28T16:05:00', '2026-06-29T09:00:00', 2, N'Inventario validado correctamente.');
INSERT INTO TbRevisionTarea (IdTarea, IdRevisor, FechaEnvio, FechaRevision, IdResultadoRevision, Comentario) VALUES (5, 1, '2026-07-14T15:05:00', '2026-07-15T09:00:00', 2, N'Catálogo aprobado.');
INSERT INTO TbRevisionTarea (IdTarea, IdRevisor, FechaEnvio, FechaRevision, IdResultadoRevision, Comentario) VALUES (18, 1, '2026-08-20T09:00:00', '2026-08-20T14:00:00', 3, N'Revisar registros sin identificador antes de finalizar.');
INSERT INTO TbRevisionTarea (IdTarea, IdRevisor, FechaEnvio, FechaRevision, IdResultadoRevision, Comentario) VALUES (13, 1, '2026-08-04T15:05:00', '2026-08-05T08:30:00', 2, N'Piezas aprobadas.');
INSERT INTO TbRevisionTarea (IdTarea, IdRevisor, FechaEnvio, FechaRevision, IdResultadoRevision, Comentario) VALUES (49, 3, '2026-07-24T15:05:00', '2026-07-25T09:00:00', 2, N'Catálogo de hallazgos aprobado.');
GO

INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (1, 1, N'Revisar que las reglas de seguridad estén documentadas antes de aprobar.', '2026-08-28T11:00:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (1, 6, N'La documentación de seguridad fue adjuntada.', '2026-08-28T12:00:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (3, 1, N'Priorizar la ventana de mantenimiento para esta semana.', '2026-08-18T14:00:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (10, 1, N'Solicitar los anexos pendientes al área jurídica.', '2026-08-13T10:00:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (14, 7, N'Programación revisada con Mercadeo.', '2026-08-27T15:00:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (18, 1, N'Validar los registros sin documento antes de cerrar la tarea.', '2026-08-27T16:00:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (7, 8, N'Falta confirmar mensaje de escalamiento.', '2026-08-24T16:00:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (11, 9, N'Administración ya validó los cambios.', '2026-08-24T16:30:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (22, 6, N'Se revisaron los auxiliares con mayor saldo.', '2026-08-25T15:00:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (26, 1, N'Mantener el diseño consistente con Panel de gestión.', '2026-08-27T15:30:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (31, 6, N'Segmentos principales ya fueron migrados.', '2026-08-27T16:00:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (34, 9, N'Se confirmó disponibilidad para la próxima jornada.', '2026-08-27T16:10:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (38, 7, N'El avance de digitalización fue revisado.', '2026-08-28T09:00:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (50, 6, N'Formulario de controles ya permite registrar hallazgos.', '2026-08-27T17:00:00');
INSERT INTO TbComentarioTarea (IdTarea, IdUsuario, Comentario, FechaComentario) VALUES (57, 9, N'Faltan dos procesos secundarios por documentar.', '2026-08-28T14:00:00');
GO

INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 3, N'Nueva tarea asignada', N'Se asignó la tarea Configurar ambiente de nube.', 1, 1, 1, 1, '2026-07-01T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 5, N'Recordatorio de avance', N'Registre el avance de Configurar ambiente de nube.', 2, 1, 1, 0, '2026-08-20T09:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 3, N'Nueva tarea asignada', N'Se asignó la tarea Validar respaldos en nube.', 2, 4, 1, 1, '2026-08-01T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 3, N'Nueva tarea asignada', N'Se asignó la tarea Definir catálogo de solicitudes.', 2, 5, 2, 1, '2026-06-15T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 3, N'Nueva tarea asignada', N'Se asignó la tarea Revisar cláusulas de renovación.', 1, 10, 3, 1, '2026-07-01T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 1, N'Tarea vencida', N'Revisar cláusulas de renovación superó la fecha límite.', 1, 10, 3, 0, '2026-08-16T08:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 3, N'Nueva tarea asignada', N'Se asignó la tarea Revisar métricas iniciales.', 3, 15, 4, 0, '2026-08-20T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 3, N'Nueva tarea asignada', N'Se asignó la tarea Depurar clientes duplicados.', 1, 18, 5, 1, '2026-07-01T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 5, N'Recordatorio de depuración', N'Quedan registros pendientes de validación manual.', 2, 18, 5, 0, '2026-08-28T08:30:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 2, N'Tarea devuelta para corrección', N'Revisar registros sin identificador antes de finalizar.', 1, 18, 5, 0, '2026-08-20T14:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 3, N'Nueva tarea asignada', N'Se asignó la tarea Revisar auxiliares contables.', 2, 22, 6, 1, '2026-08-01T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 3, N'Nueva tarea asignada', N'Se asignó la tarea Diseñar tablero principal.', 2, 26, 7, 1, '2026-08-05T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 5, N'Recordatorio del portal', N'Actualice el avance del diseño del tablero.', 3, 26, 7, 0, '2026-08-28T09:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 3, N'Nueva tarea asignada', N'Se asignó la tarea Reconfigurar red interna.', 1, 31, 8, 1, '2026-08-15T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 5, N'Recordatorio de red', N'La reconfiguración debe completarse antes del siguiente hito.', 2, 31, 8, 0, '2026-08-27T08:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (6, 3, N'Nueva tarea asignada', N'Se asignó la tarea Desarrollar registro de controles.', 1, 50, 13, 0, '2026-07-15T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (1, 4, N'Proyecto crítico', N'Migración a nube institucional requiere seguimiento.', 1, NULL, 1, 0, '2026-08-28T08:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (1, 4, N'Proyecto crítico', N'Depuración de datos maestros presenta retrasos.', 1, NULL, 5, 0, '2026-08-28T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (1, 5, N'Revisión pendiente', N'Configurar ambiente de nube está pendiente de revisión.', 1, 1, 1, 0, '2026-08-28T10:10:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (1, 5, N'Revisión pendiente', N'Construir módulo de reportes está pendiente de revisión.', 2, 6, 2, 0, '2026-08-29T09:10:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (1, 4, N'Contrato próximo a cierre', N'Actualización de contratos entra en su etapa final.', 2, NULL, 3, 0, '2026-08-27T10:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (1, 4, N'Avance de campaña', N'Campaña institucional se encuentra en ejecución.', 3, NULL, 4, 1, '2026-08-26T10:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (1, 4, N'Cierre financiero', N'Revisar avance de conciliaciones preliminares.', 2, NULL, 6, 0, '2026-08-26T11:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (1, 4, N'Portal de indicadores', N'El prototipo debe validarse en septiembre.', 3, NULL, 7, 0, '2026-08-28T11:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (1, 4, N'Infraestructura retrasada', N'La entrega de equipos afecta el cronograma.', 1, NULL, 8, 0, '2026-08-19T10:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (1, 5, N'Revisar avances recientes', N'Hay nuevos avances registrados por el equipo.', 3, NULL, NULL, 0, '2026-08-29T08:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (7, 5, N'Revisión pendiente', N'El módulo de reportes fue enviado a revisión.', 2, 6, 2, 0, '2026-08-29T09:10:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (8, 1, N'Tarea vencida', N'Migrar base de datos principal se encuentra vencida.', 1, 3, 1, 0, '2026-08-21T08:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (8, 1, N'Tarea vencida', N'Depurar proveedores se encuentra vencida.', 1, 19, 5, 0, '2026-08-19T08:00:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (7, 3, N'Nueva tarea asignada', N'Se asignó la tarea Desarrollar filtros del portal.', 3, 27, 7, 0, '2026-08-20T08:05:00');
INSERT INTO TbNotificacion (IdUsuario, IdTipoNotificacion, Titulo, Mensaje, IdPrioridad, IdTarea, IdProyecto, Leida, FechaCreacion) VALUES (8, 3, N'Nueva tarea asignada', N'Se asignó la tarea Preparar casos de prueba.', 2, 51, 13, 0, '2026-08-15T08:05:00');

SELECT * FROM TbProyecto WHERE Codigo = 'cft-102';
SELECT * FROM TbProyecto;